### ISSUE TITLE
Wiser hub can return non printable chars

### ISSUE THREAD

**Issue by asantaga** [msp1974/wiserHeatAPIv2#1]
Related to https://github.com/asantaga/wiserHomeAssistantPlatform/issues/205 , the heathub can return non printable chars. We had this issue in V1 and it was solved by this PR https://github.com/asantaga/wiserheatingapi/pull/16/files

I think these changes to  https://github.com/msp1974/wiserHeatAPIv2/blob/master/wiserHeatAPIv2/rest_controller.py will fix it 

line 18      :  import re
line 87      :  return  re.sub(rb'[^\x20-\x7F]+', b'', response.json())

**Comment by msp1974** [comment]
Fixed in 0.0.15 release
