### ISSUE TITLE
install version 0.0.27

### ISSUE THREAD

**Issue by LGO44** [msp1974/wiserHeatAPIv2#10]
@msp1974 
I try to install this version on my virtual machine from the dev branch, it' s seemed to succeed  

![Capture d’écran 2022-03-30 à 15 50 31](https://user-images.githubusercontent.com/95585425/160851041-dbfc7570-23b8-499a-bac0-b34ab6276527.png)

When I restart HA after modify manifest.json to use it: 
"requirements": ["wiserHeatAPIv2==0.0.27"],

I get an issue: 
_2022-03-30 15:47:19 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package wiserHeatAPIv2==0.0.27: ERROR: Could not find a version that satisfies the requirement wiserHeatAPIv2==0.0.27 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26)
ERROR: No matching distribution found for wiserHeatAPIv2==0.0.27
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2022-03-30 15:47:20 INFO (SyncWorker_5) [homeassistant.util.package] Attempting install of wiserHeatAPIv2==0.0.27_

When I do the same process from the master branch of /msp1974/wiserHeatAPIv2 (v0.0.26) everything run fine.

What is my error?
Thanks 
Christian

**Comment by msp1974** [comment]
Closing this as old issue now solved
