### ISSUE TITLE
Add some opentherm statistics

### ISSUE THREAD

**Issue by psblah** [msp1974/wiserHeatAPIv2#15]
Hello!

Just wanted to add some opentherm statistics, I have an opentherm connection, and thought i'd have a crack:

https://github.com/psblah/wiserHeatAPIv2/pull/1

Seems to work pulling those few number i've added. Not sure what the best way to integrate this would be!

**Comment by msp1974** [comment]
Can you send it to me as a PR and ill look to include this in a new release.  Thx

**Comment by msp1974** [comment]
Sorry just seen you did but closed it.  Have reopened so i can review and merge.  Thanks for submitting

**Comment by msp1974** [comment]
Closing this as in the api.  Updated the integration issue to say will be in next release.  Thanks

**Comment by psblah** [comment]
again, legend! thanks for adding it in so quickly 👍 
this let's me see if my central heating pipework is leaking anywhere.
