### ISSUE TITLE
required version of ruamel.yaml doesn't install on python 3.10.2

### ISSUE THREAD

**Issue by mzealey** [msp1974/wiserHeatAPIv2#2]
I get a ton of compile errors when trying to install 0.0.16 or 0.0.17 on python 3.10.2 due to ruamel.yaml not compiling. Using a more recent version of the lib (eg 0.17.20) installs fine. Can you bump the dep to that ?

**Comment by msp1974** [comment]
Yes I can look at this. Have you fully tested the schedule functions with this version of ruamel?

**Comment by mzealey** [comment]
To be honest I've not used the schedule functions at all so I wouldn't really know how to test them. The download via HA to YAML file certainly works correctly. The main issue is having to hack all the deps in order to make this work on python 3.10

**Comment by msp1974** [comment]
Just released 0.0.20 version of the api which now uses ruamel.yaml 0.17.20.

**Comment by msp1974** [comment]
@mzealey Just to let you know that I have had to downgrade ruamel.yaml to v0.16.12 as we had many issues installing this in HA with the integration it is built to support on 0.17.20.  I checked it on Python 3.10 and did not have issues but if you could let me know if it works or not for you.  thanks

**Comment by mzealey** [comment]
Yes this seems to be working OK - installed via HACS rather than having to manually install and hack deps previously. Thanks!
