### ISSUE TITLE
Error setup v0.21

### ISSUE THREAD

**Issue by LGO44** [msp1974/wiserHeatAPIv2#3]
To install the wiserHeatAPIv2, I mad these command in the terminal session in HA

# **clone** the GitHub in HA

![image](https://user-images.githubusercontent.com/95585425/154698301-0452ad06-19c1-4ab6-9f06-0d1b793fe460.png)

#  **ls** command

![image](https://user-images.githubusercontent.com/95585425/154699025-830a8b89-801e-433c-a120-2c7553079e10.png)

# command **python3 setup.py install**
![image](https://user-images.githubusercontent.com/95585425/154700216-b25c2e43-08f6-40d2-897f-8416a25ea3f1.png)
# Result 
the install process ended with an error:
![image](https://user-images.githubusercontent.com/95585425/154697965-0090e889-8925-4db7-be06-42c18b1e8bb7.png)

# ls command
![image](https://user-images.githubusercontent.com/95585425/154702205-66c9795a-d38a-4091-a1e3-1ad1c5c9e9e6.png)

Thanks for your help

**Comment by msp1974** [comment]
You need to install the following in your dev environment through apt/apk etc (depends on linux version)
```
gcc 
musl-dev 
python3-dev
```
See https://github.com/asantaga/wiserHomeAssistantPlatform/issues/232

It is to do with ruamel.yaml needed for the schedule imports/exports etc.  Not sure what your dev environment is (linux version etc) but it is trying to compile it as pip doesn't have a precompiled version available.

**Comment by LGO44** [comment]
@msp1974 
I finally managed to install wiserHeatAPIv2. Thanks to your help.
I created a document to follow the step.

[Install wiserHeatAPIv2.pdf](https://github.com/msp1974/wiserHeatAPIv2/files/8100727/Install.wiserHeatAPIv2.pdf)

Sorry for the inconvenience and thank you for your understanding and efficiency.

**Comment by msp1974** [comment]
@LGO44 - your dev environment is not the right way to run a dev environment for HA.  This is actually a way to run a deployed version, it is running HA in a docker container, not on the base OS and the terminal session you are running in not actually in the HA python environment, therefore, whilst what you are doing is correct to install wiserHeatAPIv2, you are not actually installing it into the python environment that HA is using.

My recommendation would be to build a linux environment in vbox (I run under and Ubuntu environment with a GUI), and then follow the instructions on the link I gave you about setting up a dev environment (looks like you were trying to do this within the Hass OS environment - which is very wrong).

Once you have a base Ubuntu install, then follow the instructions on this link.  You should not have any HA environment before you follow these instructions.

https://developers.home-assistant.io/docs/development_environment/#setup-local-repository
