### ISSUE TITLE
Lights and shutters dev

### ISSUE THREAD

**Issue by LGO44** [msp1974/wiserHeatAPIv2#4]
I've made some modifications in the API to manage the lights and shutters. 

I fixed an issue for the command request LiftTo

**Comment by msp1974** [comment]
OK I have added the fix for the current_lift you picked up and also found the error for schedule_id and fixed that.  0.0.25 is on the master branch so you can update your fork from this.  

We probably need to align on how to send the work you are doing to me using Pull Requests as this will make it much easier to keep in sync.

**Comment by msp1974** [comment]
I have also now included all the changes you have made to the api into the master branch on my repo (v0.0.25), except 2.

You have put the available_modes in the collection class.  I don't think this is a good idea as we may get different light/shutter types going forward which may have different available_modes.  This property is available on the actual light/shutter and should be used from there.

**Comment by LGO44** [comment]
I have put the available_modes in the collection class because i got an error and the system advise me to put it there….

2022-03-09 14:42:49 INFO (MainThread) [homeassistant.components.light] Setting up light.wiser
2022-03-09 14:42:50 ERROR (MainThread) [homeassistant.components.select] Error while setting up wiser platform for select
Traceback (most recent call last):
  File "/home/christian/development/core/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/christian/development/core/custom_components/wiser/select.py", line 100, in async_setup_entry
    vol.Required(ATTR_MODE): vol.In(data.wiserhub.devices.lights.available_modes),
AttributeError: '_WiserLightCollection' object has no attribute 'available_modes'
2022-03-09 14:42:50 INFO (MainThread) [custom_components.wiser.light] WiserHeat03F9E3 Lustre init

**Comment by msp1974** [comment]
OK I see now and I actually did this on smartplugs! ;-) Ok will put this in too.

**Comment by LGO44** [comment]
@msp1974 
OK Mark, I always draw inspiration from the code you produced to give some consistency, to be able to join it to the integration (API and Wiser Integration).

**Comment by msp1974** [comment]
this should be fixed now
