### ISSUE TITLE
Schedules : save in yaml files for light and shutter

### ISSUE THREAD

**Issue by LGO44** [msp1974/wiserHeatAPIv2#6]
during me tests for Lights and shutters I wanted to save the schedules
I've got an error:

_2022-03-10 14:30:48 INFO (MainThread) [custom_components.wiser.cover] Saving Volet schedule to file volet_prog.yaml
2022-03-10 14:30:48 ERROR (SyncWorker_2) [wiserHeatAPIv2] Error converting from Wiser schedule: unconverted data remains: 0_

The cause is, in my schedule, I don't use  time of the day but only sunrise ans sunset that give 3000 and 4000 in the schedule therefore not convertible
[schedules-20220310-144713.zip](https://github.com/msp1974/wiserHeatAPIv2/files/8224054/schedules-20220310-144713.zip)
.

**Comment by msp1974** [comment]
Ah so that is what 3000 & 4000 are!  I did wonder when looking at your original json hub output.

I am doing some rework on this part of the api as with these new schedule types, it does not really work too well.  I'll let you know when I am done (give me a few days) so that you can update it and test.

**Comment by msp1974** [comment]
Sorry, should have added that as part of these changes to the save/set schedule api, I intent to also change the save/set services in the integration, otherwise I think it will be very cumbersome and complex.  The end goal I have is to just have 1 save and 1 set service for any schedule that checks you are setting it from the correct schedule type.

As such, the service setup you have added to lights.py and covers.py will not be needed or will need to change.

If you can look at the issue I posted regarding forking the main wiserHomeAssistantPlatform repo and adding your changes into that fork, we can then ensure that this all joins together.

Thanks

**Comment by LGO44** [comment]
you 're welcome.
That's also why I don't try to do any modification

**Comment by msp1974** [comment]
Ok, I have made quite a lot of changes to how the integration deals with the schedule services to make it much simpler.  However, for now, I had had to leave the previous method in there but with a deprecation warning.

So for your lights and shutters, you need to do the following to support schedule services (Save, Set, Copy).

I will use light.py as the example but same applies for cover.py.  All this will need the latest version of the dev branch for WiserHomeAssistantPlatform and the latest v0.0.25 WiserHeatAPI from the repo.

1) Remove code relating to services setup
ie - all this
```
# Setup services
        platform = entity_platform.async_get_current_platform()

    
        platform.async_register_entity_service(
            WISER_SERVICES["SERVICE_GET_LIGHT_SCHEDULE"],
            {
                vol.Optional(ATTR_FILENAME, default=""): vol.Coerce(str),
            },
            "async_get_schedule"
            )

        platform.async_register_entity_service(
            WISER_SERVICES["SERVICE_SET_LIGHT_SCHEDULE"],
            {
                vol.Optional(ATTR_FILENAME, default=""): vol.Coerce(str),
            },
            "async_set_schedule"
            )

        platform.async_register_entity_service(
            WISER_SERVICES["SERVICE_COPY_LIGHT_SCHEDULE"],
            {
                vol.Required(ATTR_COPYTO_ENTITY_ID): cv.entity_id,
            },
            "async_copy_schedule"
            )
```

2) Remove functions for get,set,copy
ie - all this
```
@callback
    async def async_get_schedule(self, filename: str) -> None:
        try:
            if self._light.schedule:
                _LOGGER.info(f"Saving {self._light.name} schedule to file {filename}")
                await self.hass.async_add_executor_job(
                    self._light.schedule.save_schedule_to_yaml_file, filename
                )
            else:
                _LOGGER.warning(f"{self._light.name} has no schedule to save")
        except:
            _LOGGER.error(f"Saving {self._light.name} schedule to file {filename}")

    @callback
    async def async_set_schedule(self, filename: str) -> None:
        try:
            if self._light.schedule:
                _LOGGER.info(f"Setting {self._light.name} schedule from file {filename}")
                await self.hass.async_add_executor_job(
                    self._light.schedule.set_schedule_from_yaml_file, filename
                )
                await self.async_force_update()
            else:
                _LOGGER.warning(f"{self._light.name} has no schedule to assign")
        except:
            _LOGGER.error(f"Error setting {self._light.name} schedule from file {filename}")

    @callback
    async def async_copy_schedule(self, to_entity_id)-> None:
        to_light_name = to_entity_id.replace("light.wiser_","").replace("_"," ")
        try:
            if self._light.schedule:
                # Add Check that to_entity is of same type as from_entity
                _LOGGER.info(f"Copying schedule from {self._light.name} to {to_light_name.title()}")
                await self.hass.async_add_executor_job(
                    self._light.schedule.copy_schedule, self._data.wiserhub.lights.get_by_name(to_light_name).schedule.id
                )
                await self.async_force_update()
            else:
                _LOGGER.warning(f"{self._light.name} has no schedule to copy")
                
        except:
            _LOGGER.error(f"Error copying schedule from {self._light.name} to {to_light_name}")
```

## Now to add the services capability.

3) Import the WiserScheduleEntity class at the top of the file
ie
```
from .schedules import WiserScheduleEntity
```
3) Add the WiserScheduleEntity class to your light class
ie
```
class WiserLight(LightEntity, WiserScheduleEntity):
```

4) Add a property for the schedule called self._schedule in the __init__ method on your WiserLight class and update this property in the async_update method.
ie
```
class WiserLight(LightEntity, WiserScheduleEntity):
    """WiserLight ClientEntity Object."""

    def __init__(self, data, light_id):
        """Initialize the sensor."""
        self._data = data
        self._light_id = light_id
        self._light = self._data.wiserhub.devices.lights.get_by_id(self._light_id)
        self._name = self._light.name
        self._schedule = self._light.schedule

        _LOGGER.info(f"{self._data.wiserhub.system.name} {self.name} init")

    async def async_force_update(self):
        _LOGGER.debug(f"{self._light.name} requested hub update")
        await self._data.async_update(no_throttle=True)

    async def async_update(self):
        """Async update method."""
        self._light = self._data.wiserhub.devices.lights.get_by_id(self._light_id)
        self._schedule = self._light.schedule
```

Now if you use the Save Schedule to File, Set Schedule From File or Copy Schedule services on the light entity it should work.

I have tested it but it is possible there are still some bugs, so let me know.

**Comment by LGO44** [comment]
#msp1974
hello Mark, I have i addition of my dev environment running on a virtual machin Ubuntu , my Home Assistant running on a raspberry PI 4.
I want to install the last version of the API on my raspberry : 

- clone the repository in the config folder
- in :config/wiserHeatAPIv2   pip install -e .
the result seem to be right 

When I restart the raspberry , the API version is always v 0.0.23  came with WiserPlatform v 3.0.22

What it the right way to install the API , independly from the wiser platform?
Thanks 
Christian

**Comment by msp1974** [comment]
Change your manifest.json file to use the 0.0.25 version of the api as each time you restart HA it will download the version listed there.Sent from my Galaxy

**Comment by LGO44** [comment]
OK done 👍 
In France we are better at rugby than programming...
